---
title: "Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(logistic.regression)
```

Simple Logistic Regression (2 Predictors, no interaction)
```{r}
set.seed(100) #keep track of specific sample
n <- 200
x1 <- rnorm(n)
x2 <- rbinom(n, size=1, prob=0.5)
beta_true <- c(Intercept = 0.5, x1 = -1.5, x2 = 0.8) #true coefficients
eta <- beta_true["Intercept"] + beta_true["x1"] * x1 + beta_true["x2"] * x2
p <- 1 / (1 + exp(-eta)) #probabilities
y <- rbinom(n, size = 1, prob = p) #binary y response variable
data <- data.frame(y = y, x1 = x1, x2 = factor(x2)) #format into data frame 
```

```{r}
#my_logregr function fit
my_logreg_fit <- my_logregr(y ~ x1 + x2, data)
#glm built-in function fit
og_glm_fit <- glm(y ~ x1+x2, data, family = binomial)

# Convert coefficients to numeric vector and set names
my_coefficients <- as.numeric(my_logreg_fit$coefficients)
glm_coefficients <- as.numeric(coef(og_glm_fit))

# Coefficient comparison
all.equal(my_coefficients, glm_coefficients, tolerance = 1e-6)
```
Interaction Logistic Regression (2 predictors, 1 interaction)
```{r}
#Utilizing same data as previous example, adding an interaction covariate
data$x1_x2 <- data$x1 * as.numeric(as.character(data$x2))
# Fit the model with interaction using my_logistic_regression
inter_my_fit <- my_logregr(y ~ x1 + x2 + x1:x2, data)
inter_glm_fit <- glm(y ~ x1+x2 + x1:x2, data, family = binomial)

# Convert coefficients to numeric vector and set names
inter_my_coefficients <- as.numeric(inter_my_fit$coefficients)
inter_glm_coefficients <- as.numeric(coef(inter_glm_fit))

# Coefficient comparison
all.equal(inter_my_coefficients, inter_glm_coefficients, tolerance = 1e-6)
```



Benchmarking Efficiency
```{r}
bench::mark(og_glm_fit, my_logreg_fit, check=FALSE)
```



